"""add location field to days

Revision ID: dc89b2a25ef9
Revises: c17792c725e5
Create Date: 2026-09-17 01:27:27.050850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc89b2a25ef9'
down_revision: Union[str, Sequence[str], None] = 'c17792c725e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'location')
    # ### end Alembic commands ###
